test1 modification - displaying line numbers in error messages

diff --git a/tests/spiatek/test1 b/tests/spiatek/test1
--- a/tests/spiatek/test1
+++ b/tests/spiatek/test1
@@ -1,5 +1,21 @@
 #!/bin/bash
 
+$SHDIR=`dirname $0`
+
+mkdir filesystem
+
+echo '----------------------------------------------'
+echo '---                Montowanie              ---'
+echo '----------------------------------------------'
+echo -e "\n"
+
+python ~/cumulonimbus/cumulonimbus/cfuse.py filesystem -o authurl='http://127.0.0.1:8080/auth/v1.0' -o user='test:tester' -o key='testing'
+
+if [ $? -ne 0 ]
+then 
+	exit 1
+fi
+
 echo '----------------------------------------------'
 echo '---           Tworzenie katalogów          ---'
 echo '----------------------------------------------'
@@ -9,31 +25,31 @@ mkdir filesystem 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\nmkdir error\n"
+  echo -e "\n$LINENO: mkdir error\n"
 fi
 
 mkdir filesystem/dir1 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmkdir error\n"
+  echo -e "\n$LINENO: mkdir error\n"
 fi
 
 mkdir filesystem/dir2 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmkdir error\n"
+  echo -e "\n$LINENO: mkdir error\n"
 fi
 
 mkdir filesystem/dir3 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmkdir error\n"
+  echo -e "\n$LINENO: mkdir error\n"
 fi
 
-./test_ls_tree
+bash $SHDIR/test_ls_tree
 
 echo '----------------------------------------------'
 echo '---      Tworzenie struktury katalogów     ---'
@@ -44,24 +60,24 @@ mkdir filesystem/dir1/dir4 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\nmkdir error\n"
+  echo -e "\n$LINENO: mkdir error\n"
 fi
 
 mkdir filesystem/dir1/dir5 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmkdir error\n"
+  echo -e "\n$LINENO: mkdir error\n"
 fi
 
 mkdir filesystem/dir2/dir6 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\nmkdir error\n"
+  echo -e "\n$LINENO: mkdir error\n"
 fi
 
-./test_ls_tree
+bash $SHDIR/test_ls_tree
 
 echo '----------------------------------------------'
 echo '---            Tworzenie plików            ---'
@@ -72,24 +88,24 @@ touch filesystem/dir3/file1 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\ntouch error\n"
+  echo -e "\n$LINENO: touch error\n"
 fi
 
 touch filesystem/dir3/file2 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\ntouch error\n"
+  echo -e "\n$LINENO: touch error\n"
 fi
 
 touch filesystem/dir3/file3 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\ntouch error\n"
+  echo -e "\n$LINENO: touch error\n"
 fi
 
-./test_ls_tree
+bash $SHDIR/test_ls_tree
 
 echo '----------------------------------------------'
 echo '---      Wyświetlenie pustych plików       ---'
@@ -99,7 +115,7 @@ cat filesystem/dir3/file1 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\ncat error\n"
+  echo -e "\n$LINENO: cat error\n"
 fi
 
 echo '----------------------------------------------'
@@ -110,7 +126,7 @@ cat filesystem/dir1/dir4 2> /dev/null
 
 if [ $? -eq 0 ] 
 then 
-  echo -e "\ncat error\n"
+  echo -e "\n$LINENO: cat error\n"
 fi
 
 echo '----------------------------------------------'
@@ -121,66 +137,66 @@ mv filesystem/dir1 filesystem/folder1 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
 mv filesystem/dir2 filesystem/folder2 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
 mv filesystem/dir3 filesystem/folder3 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
 mv filesystem/folder3/file1 filesystem/folder3/plik1 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
 mv filesystem/folder3/file2 filesystem/folder3/plik2 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
 mv filesystem/folder3/file3 filesystem/folder3/plik3 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
 mv filesystem/folder1/dir4 filesystem/folder1/folder4 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
 mv filesystem/folder1/dir5 filesystem/folder1/folder5 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
 mv filesystem/folder2/dir6 filesystem/folder2/folder6 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
-./test_ls_tree
+bash $SHDIR/test_ls_tree
 
 echo '----------------------------------------------'
 echo '---          Przenoszenie plików           ---'
@@ -190,38 +206,38 @@ mv filesystem/folder3/plik1 filesystem/folder2 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
 mv filesystem/folder3/plik2 filesystem/folder2 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
 mv filesystem/folder3/plik3 filesystem/folder2 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
 mv filesystem/folder2/folder6 filesystem 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
 mv filesystem/folder2/* filesystem/folder6 2> /dev/null
 
 if [ $? -ne 0 ] 
 then 
-  echo -e "\nmv error\n"
+  echo -e "\n$LINENO: mv error\n"
 fi
 
-./test_ls_tree
+bash $SHDIR/test_ls_tree
 
 echo '----------------------------------------------'
 echo '---           Kopiowanie plików            ---'
@@ -231,38 +247,38 @@ cp filesystem/folder6/plik1 filesystem/folder1 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\ncp error\n"
+  echo -e "\n$LINENO: cp error\n"
 fi
 
 cp filesystem/folder6/plik2 filesystem/folder1 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\ncp error\n"
+  echo -e "\n$LINENO: cp error\n"
 fi
 
 cp filesystem/folder6/plik3 filesystem/folder1 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\ncp error\n"
+  echo -e "\n$LINENO: cp error\n"
 fi
 
 cp filesystem/folder6/plik1 filesystem 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\ncp error\n"
+  echo -e "\n$LINENO: cp error\n"
 fi
 
 cp filesystem/folder6/* filesystem/folder1/folder4 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\ncp error\n"
+  echo -e "\n$LINENO: cp error\n"
 fi
 
-./test_ls_tree
+bash $SHDIR/test_ls_tree
 
 echo '----------------------------------------------'
 echo '---             Usuwanie plików            ---'
@@ -272,14 +288,14 @@ rm filesystem/folder1/plik* 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\nrm error\n"
+  echo -e "\n$LINENO: rm error\n"
 fi
 
 rm -R filesystem/folder1/folder4 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\nrm error\n"
+  echo -e "\n$LINENO: rm error\n"
 fi
 
 echo '----------------------------------------------'
@@ -290,34 +306,10 @@ rm folder3 2&> /dev/null
 
 if [ $? -eq 0 ]
 then 
-  echo -e "\nrm error\n"
+  echo -e "\n$LINENO: rm error\n"
 fi
 
-./test_ls_tree
-
-echo '----------------------------------------------'
-echo '---                Montowanie              ---'
-echo '----------------------------------------------'
-
-#sudo mount ? filesystem/folder1/folder5 2> /dev/null
-
-#if [ $? -ne 0 ]
-#then 
-#  echo -e "\nmount error\n"
-#fi
-#
-#sleep 10
-
-echo '----------------------------------------------'
-echo '---              Demontowanie              ---'
-echo '----------------------------------------------'
-
-#sudo umount filesystem/folder1/folder5 2> /dev/null
-#
-#if [ $? -ne 0 ]
-#then 
-#  echo -e "\numount error\n"
-#fi
+bash $SHDIR/test_ls_tree
 
 echo '----------------------------------------------'
 echo '---          Utworzenie dowiązania         ---'
@@ -327,10 +319,10 @@ ln -s filesystem/folder1 filesystem/link1 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\nln error\n"
+  echo -e "\n$LINENO: ln error\n"
 fi
 
-./test_ls_tree
+bash $SHDIR/test_ls_tree
 
 echo '----------------------------------------------'
 echo '---        Usuwanie systemu plików         ---'
@@ -342,15 +334,20 @@ rm -R filesystem/* 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\nrm error\n"
+  echo -e "\n$LINENO: rm error\n"
 fi
 
-./test_ls_tree
+bash $SHDIR/test_ls_tree
 
 rm -R filesystem 2> /dev/null
 
 if [ $? -ne 0 ]
 then 
-  echo -e "\nrm error\n"
+  echo -e "\n$LINENO: rm error\n"
 fi
 
+echo '----------------------------------------------'
+echo '---              Demontowanie              ---'
+echo '----------------------------------------------'
+
+fusermount -u filesystem
